/**
 * Comprehensive tech skills list organized by category
 * Used in both MyProfile (candidate) and CreateJob (recruiter) pages
 */

export const TECH_SKILLS = {
  "Programming Languages": [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "C#",
    "Go (Golang)",
    "Rust",
    "PHP",
    "Ruby",
    "Kotlin",
    "Swift",
    "R",
    "MATLAB",
    "Scala",
    "Dart",
    "Bash",
    "Shell",
  ],
  "Web Development (Frontend)": [
    "HTML",
    "CSS",
    "JavaScript (ES6+)",
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "Tailwind CSS",
    "Bootstrap",
    "Sass",
    "SCSS",
    "Redux",
    "Zustand",
    "Recoil",
    "React Query",
    "TanStack Query",
    "Webpack",
    "Vite",
    "Babel",
    "Storybook",
  ],
  "Backend Development": [
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Hapi.js",
    "Deno",
    "Bun",
    "FastAPI",
    "Django",
    "Django REST Framework (DRF)",
    "Flask",
    "Sanic",
    "Tornado",
    "Spring",
    "Spring Boot",
    "Hibernate",
    "Micronaut",
    "Quarkus",
    ".NET",
    "ASP.NET Core",
    "Entity Framework",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "Yii",
    "Gin",
    "Fiber",
    "Echo",
    "Beego",
    "Ruby on Rails",
    "Sinatra",
    "Actix",
    "Rocket",
    "Axum",
    "GraphQL",
    "REST APIs",
    "gRPC",
    "WebSockets",
    "Microservices Architecture",
    "Monolithic Architecture",
    "Event-driven Architecture",
  ],
  "Databases & Storage": [
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Oracle DB",
    "SQL Server",
    "MongoDB",
    "Redis",
    "Cassandra",
    "DynamoDB",
    "Firebase Firestore",
    "CouchDB",
    "Elasticsearch",
    "OpenSearch",
  ],
  "Cloud & DevOps": [
    "AWS",
    "EC2",
    "S3",
    "RDS",
    "Lambda",
    "ECS",
    "EKS",
    "Google Cloud Platform (GCP)",
    "Microsoft Azure",
    "Serverless (Lambda, Cloud Functions)",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Jenkins",
    "DevOps",
    "Terraform",
    "Ansible",
    "Nginx",
    "Apache",
    "Kafka",
    "RabbitMQ",
  ],
  "AI / Machine Learning": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Large Language Models (LLMs)",
    "OpenAI API",
    "Google Gemini",
    "Prompt Engineering",
    "Model Fine-tuning",
    "Embeddings",
    "Vector Search",
    "Semantic Search",
    "Vector Databases",
    "FAISS",
    "Pinecone",
    "Chroma",
    "Retrieval-Augmented Generation (RAG)",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Hugging Face",
  ],
  "Data & Analytics": [
    "Data Analysis",
    "Data Engineering",
    "Data Science",
    "Data Warehousing",
    "ETL Pipelines",
    "SQL Optimization",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Power BI",
    "Tableau",
    "Excel (Advanced)",
    "Apache Spark",
    "Hadoop",
    "Airflow",
  ],
  "Mobile Development": [
    "Android Development",
    "iOS Development",
    "React Native",
    "Flutter",
    "SwiftUI",
    "Jetpack Compose",
  ],
  Cybersecurity: [
    "Network Security",
    "Web Security",
    "API Security",
    "Penetration Testing",
    "Ethical Hacking",
    "Cryptography",
    "JWT",
    "OAuth 2.0",
    "OpenID Connect",
    "Session-based Authentication",
    "Role-Based Access Control (RBAC)",
    "HTTPS",
    "TLS",
    "CORS",
    "CSRF Protection",
    "bcrypt",
    "Argon2",
    "OWASP Top 10",
    "SIEM",
    "SOC Tools",
  ],
  "Software Engineering": [
    "Data Structures & Algorithms",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "Design Patterns",
    "SOLID Principles",
    "Clean Code",
    "System Design",
    "API Design",
    "Distributed Systems",
    "Operating Systems",
    "Computer Networks",
    "Database Design",
  ],
  "Testing & QA": [
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Load Testing",
    "PyTest",
    "JUnit",
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Playwright",
    "Selenium",
    "JMeter",
    "Locust",
    "Test Automation",
  ],
  "Version Control": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Agile / Scrum",
    "Jira",
    "Confluence",
    "Notion",
  ],
  "API & Integration": [
    "RESTful APIs",
    "GraphQL APIs",
    "Webhooks",
    "OAuth",
    "OpenAPI / Swagger",
    "Postman",
  ],
  "Development Tools": [
    "VS Code",
    "IntelliJ IDEA",
    "Figma",
    "Postman",
    "Git",
    "Docker Desktop",
  ],
  "Low-Code / Tools": [
    "Firebase",
    "Supabase",
    "Appwrite",
    "Retool",
    "Zapier",
    "PowerApps",
  ],
  "Emerging Skills": [
    "Generative AI",
    "AI Agents",
    "MLOps",
    "Prompt Engineering",
    "Edge Computing",
    "Web3 / Blockchain",
    "Smart Contracts (Solidity)",
    "AR / VR",
    "IoT",
  ],
  "Soft & Hybrid Skills": [
    "Problem Solving",
    "Debugging",
    "Code Review",
    "Technical Documentation",
    "Performance Optimization",
    "Scalability Planning",
  ],
};

/**
 * Flatten all skills into a single sorted array
 */
export const ALL_SKILLS = Object.values(TECH_SKILLS)
  .flat()
  .sort((a, b) => a.localeCompare(b));

/**
 * Get all categories as an array
 */
export const SKILL_CATEGORIES = Object.keys(TECH_SKILLS);
